---
language:
  - ruby
  - node_js
rvm:
  - 2.2.2
node_js:
  - iojs
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - npm install
  - npm run install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the first command below with the generated one.
before_install:
  - ./.travis_key.sh "openssl aes-256-cbc -K $encrypted_22614f3b320e_key -iv $encrypted_22614f3b320e_iv -in .deploy_key.enc -out .deploy_key -d"
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
