---
language:
  - ruby
  - node_js
rvm:
  - 2.3
node_js:
  - stable
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - npm install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the first command below with the generated one.
before_install:
  - echo -e "machine github.com\n  login $GIT_NAME  password $GIT_PASSWORD" > ~/.netrc
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
