assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  cache: true
  compress:
    css: null
    js: null

cdn_enabled: false

google_analytics: false
piwik: false
