name: Sofy Kabachek
markdown: redcarpet
pygments: true

exclude: [ 'CHANGELOG.md', 'LICENSE.txt', 'README.md', 'VERSION', 'Gemfile.lock', 'Gemfile', 'Rakefile' ]

assets:
  compress:
    css: sass
    js: uglifier

# Uncomment below to enable deploy.
:deploy:
  # either :rsync or :sftp
  :protocol: :sftp
  # domain name
  :server: ssh.sofyk.com
  # remote username
  :user: sofyk
  # remote port
  :port: 50000
  # path to remote folder where contents of _site should go
  # must have trailing slash
  :path: /home/sofyk/sofyk.com/htdocs/

# Foundation Interchange markup support added to
# Jekyll Picture Tag (https://github.com/robwierzbowski/jekyll-picture-tag)
# Uncomment below to enable responsive images.
picture:
  markup: 'interchange'
  source: pictures/_fullsize
  output: pictures
  presets:
    default:
      ppi: [ 1, 1.5, 2 ]
      source_large:
        media: '(large)'
        width: '1440'
      source_medium:
        media: '(medium)'
        width: '1280'
      source_small:
        media: '(small)'
        width: '768'
      source_default:
        width: '500'
