name: Sofy Kabachek
markdown: redcarpet
pygments: true

exclude: [ 'CHANGELOG.md', 'LICENSE.txt', 'README.md', 'VERSION', 'Gemfile.lock', 'Gemfile', 'Rakefile' ]

assets:
  compress:
    css: sass
    js: uglifier

# uncomment below to enable deploy
:deploy:
  # either :rsync or :sftp
  :protocol: :sftp
  # domain name
  :server: ssh.sofyk.com
  # remote username
  :user: sofyk
  # remote port
  :port: 50000
  # path to remote folder where contents of _site should go
  # must have trailing slash
  :path: /home/sofyk/sofyk.com/htdocs/
